# Generated by Django 5.2.4 on 2025-07-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='ip_tracking_ip_addr_3489f7_idx'), models.Index(fields=['timestamp'], name='ip_tracking_timesta_b1bb90_idx')],
            },
        ),
    ]
